#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/share/pkg.7/neuron/8.0.0/install/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/share/pkg.7/neuron/8.0.0/install/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/usr4/spclpgm/hkim1130/Desktop/rise/x86_64/.libs/libnrnmech.so" "$@"
